import {
  adminAc,
  createAccessControl,
  defaultStatements,
} from "better-auth/plugins/access";

const statement = {
  ...defaultStatements,
  course: [
    "create",
    "read",
    "update",
    "delete",
    "publish",
    "manage_admins",
    "view_analytics",
  ],
  class: ["create", "read", "update", "delete", "manage_attendance"],
  enrollment: ["enroll", "unenroll", "assign_mentor", "view_progress"],
  attachment: [
    "create",
    "read",
    "update",
    "delete",
    "grade",
    "submit",
    "view_submissions",
  ],
  video: ["create", "read", "update", "delete", "manage_timestamps"],
  doubt: ["create", "read", "update", "delete", "respond"],
  user: ["view", "update", "ban", "unban", "manage_roles"],
  file: ["upload", "download", "delete", "archive"],
  event: ["create", "read", "update", "delete", "publish"],
  notification: ["send", "read", "manage_subscriptions"],
  profile: ["view", "update"],
  bookmark: ["create", "read", "delete"],
  note: ["create", "read", "update", "delete"],
  folder: ["create", "read", "update", "delete"],
  holiday: ["create", "read", "update", "delete"],
  organization: ["create", "read", "update", "delete", "manage_members"],
  point: ["create", "read", "update", "delete"],
  push_subscription: ["create", "read", "delete"],
  response: ["create", "read", "update", "delete"],
  schedule_event: ["create", "read", "update", "delete", "publish"],
  submission: ["create", "read", "update", "delete", "grade"],
  two_factor: ["enable", "disable", "manage"],
  member: ["create", "read", "update", "delete", "change_role"],
  invitation: ["create", "read", "delete", "accept", "reject"],
  session: ["read", "revoke", "manage"],
  account: ["read", "link", "unlink", "manage"],
  verification: ["create", "verify", "manage"],
  impersonation: ["start", "stop", "manage"],
  post: ["create", "read", "update", "delete"],
} as const;

const ac = createAccessControl(statement);

// Super Admin has all permissions
const super_admin = ac.newRole({
  ...adminAc.statements,
  course: [
    "create",
    "read",
    "update",
    "delete",
    "publish",
    "manage_admins",
    "view_analytics",
  ],
  class: ["create", "read", "update", "delete", "manage_attendance"],
  enrollment: ["enroll", "unenroll", "assign_mentor", "view_progress"],
  attachment: [
    "create",
    "read",
    "update",
    "delete",
    "grade",
    "submit",
    "view_submissions",
  ],
  video: ["create", "read", "update", "delete", "manage_timestamps"],
  doubt: ["create", "read", "update", "delete", "respond"],
  user: ["view", "update", "ban", "unban", "manage_roles"],
  file: ["upload", "download", "delete", "archive"],
  event: ["create", "read", "update", "delete", "publish"],
  notification: ["send", "read", "manage_subscriptions"],
  profile: ["view", "update"],
  bookmark: ["create", "read", "delete"],
  note: ["create", "read", "update", "delete"],
  folder: ["create", "read", "update", "delete"],
  holiday: ["create", "read", "update", "delete"],
  organization: ["create", "read", "update", "delete", "manage_members"],
  point: ["create", "read", "update", "delete"],
  push_subscription: ["create", "read", "delete"],
  response: ["create", "read", "update", "delete"],
  schedule_event: ["create", "read", "update", "delete", "publish"],
  submission: ["create", "read", "update", "delete", "grade"],
  two_factor: ["enable", "disable", "manage"],
  member: ["create", "read", "update", "delete", "change_role"],
  invitation: ["create", "read", "delete", "accept", "reject"],
  session: ["read", "revoke", "manage"],
  account: ["read", "link", "unlink", "manage"],
  verification: ["create", "verify", "manage"],
  impersonation: ["start", "stop", "manage"],
  post: ["create", "read", "update", "delete"],
});

const instructor = ac.newRole({
  course: ["create", "read", "update", "publish", "view_analytics"],
  class: ["create", "read", "update", "delete", "manage_attendance"],
  enrollment: ["view_progress", "assign_mentor"],
  attachment: [
    "create",
    "read",
    "update",
    "delete",
    "grade",
    "view_submissions",
  ],
  video: ["create", "read", "update", "manage_timestamps"],
  doubt: ["read", "respond"],
  user: ["view"],
  file: ["upload", "download"],
  event: ["create", "read", "update", "publish"],
  notification: ["send", "read"],
  profile: ["view", "update"],
  bookmark: ["create", "read", "delete"],
  note: ["create", "read", "update", "delete"],
  folder: ["create", "read", "update", "delete"],
  point: ["create", "read", "update"],
  push_subscription: ["create", "read", "delete"],
  response: ["create", "read", "update"],
  schedule_event: ["create", "read", "update", "publish"],
  submission: ["read", "grade"],
  member: ["read"],
  invitation: ["read"],
  session: ["read"],
  account: ["read", "link", "unlink"],
  verification: ["verify"],
  post: ["read"],
});

const admin = ac.newRole({
  course: ["read", "update", "publish", "view_analytics"],
  class: ["read", "update", "manage_attendance"],
  enrollment: ["enroll", "unenroll", "view_progress"],
  attachment: ["read", "grade", "view_submissions"],
  video: ["read"],
  doubt: ["read", "respond"],
  user: ["view", "ban", "unban"],
  file: ["upload", "download", "archive"],
  event: ["create", "read", "update", "publish"],
  notification: ["send", "read"],
  profile: ["view"],
  bookmark: ["read"],
  note: ["read"],
  folder: ["read"],
  holiday: ["create", "read", "update"],
  organization: ["read", "update"],
  point: ["read"],
  push_subscription: ["read"],
  response: ["read"],
  schedule_event: ["read", "update"],
  submission: ["read"],
  member: ["read", "update"],
  invitation: ["create", "read"],
  session: ["read", "revoke"],
  account: ["read"],
  verification: ["verify"],
  post: ["read"],
});

const mentor = ac.newRole({
  course: ["read", "view_analytics"],
  class: ["read", "manage_attendance"],
  enrollment: ["view_progress", "assign_mentor"],
  attachment: ["read", "grade", "view_submissions"],
  video: ["read"],
  doubt: ["create", "read", "respond"],
  user: ["view"],
  file: ["upload", "download"],
  event: ["read"],
  notification: ["send", "read"],
  profile: ["view", "update"],
  bookmark: ["create", "read", "delete"],
  note: ["create", "read", "update", "delete"],
  folder: ["read"],
  point: ["create", "read", "update"],
  push_subscription: ["create", "read", "delete"],
  response: ["create", "read", "update"],
  schedule_event: ["read"],
  submission: ["read", "grade"],
  member: ["read"],
  invitation: ["read"],
  session: ["read"],
  account: ["read", "link", "unlink"],
  verification: ["verify"],
  post: ["read"],
});

const student = ac.newRole({
  course: ["read"],
  class: ["read"],
  enrollment: ["enroll"],
  attachment: ["read", "submit"],
  video: ["read"],
  doubt: ["create", "read"],
  file: ["download"],
  event: ["read"],
  notification: ["read"],
  profile: ["view", "update"],
  bookmark: ["create", "read", "delete"],
  note: ["create", "read", "update", "delete"],
  folder: ["read"],
  point: ["read"],
  push_subscription: ["create", "read", "delete"],
  response: ["create", "read"],
  schedule_event: ["read"],
  submission: ["create", "read"],
  member: ["read"],
  invitation: ["read", "accept", "reject"],
  session: ["read"],
  account: ["read", "link", "unlink"],
  verification: ["verify"],
  post: ["read"],
});

export { ac, super_admin, instructor, admin, student, mentor };
