import "@/styles/globals.css";
import type { Metadata } from "next";
import HomeLayout from "@/components/layouts/home-layout";
import getCurrentUser from "@/actions/getCurrentUser";
import CrispChatIntegration from "@/components/crisp";

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <HomeLayout currentUser={currentUser}>
      {children}
      <CrispChatIntegration />
    </HomeLayout>
  );
}

