import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Provider from "@/providers/Provider";
import getCurrentUser from "@/actions/getCurrentUser";
import HomeLayout from "@/components/layouts/home-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en" className="bg-background text-foreground">
      <body className={inter.className}>
        <Provider>
          <HomeLayout children={children} currentUser={currentUser}/>
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  );
}
