import { getCourseClasses } from "@/actions/courses";
import ClassSidebar from "@/components/classSidebar";
import "@/styles/globals.css";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Classes",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode;
    params:any
}>) {
    const classes = await getCourseClasses(params.id)
    return (
        <>
            <div className="flex">
                <ClassSidebar params={params} classes={classes}/>
                <div>{children}</div>
            </div>
        </>
    );
}

